# Simple workflow for deploying static content to GitHub Pages
name: Update projects and deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout charge sim repo
        uses: actions/checkout@v4
        with:
          repository: dzej0/threejs_charge_sim
          path: projects/charge_sim

      - name: Pull out dist folder contents and delete unnecessary files
        run: |
          rm -f './projects/charge_sim/index.html'
          cp -a ./projects/charge_sim/dist/. ./projects/charge_sim/
          find ./projects/charge_sim/* ! -name 'assets' -type d -exec rm -rf {} +
          echo DEBUG: trying to delete everything but index.html
          find ./projects/charge_sim -maxdepth 1 ! -name 'index.html' -type f -exec rm -f {} +
          echo success

      - name: Checkout pascals triangle repo
        uses: actions/checkout@v4
        with:
          repository: dzej0/custom-pascals-triangle
          path: projects/pascals_triangle

      - name: commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          if git diff --quiet; then
            echo No changes, not commiting
          else
            git add .
            git commit -m "update subpages"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/dzej0/dzej0.github.com.git HEAD:main
          fi
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
